# permissions for end users to view models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aibrix
    app.kubernetes.io/managed-by: kustomize
  name: model-model-viewer-role`
rules:
- apiGroups:
  - model.aibrix.ai
  resources:
  - models
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - model.aibrix.ai
  resources:
  - models/status
  verbs:
  - get
